### ISSUE TITLE
bug: passing proposal info as first txs make `/cosmos/tx/v1beta1/txs/block/` query failed 

### ISSUE THREAD

**Issue by beer-1** [skip-mev/block-sdk#215]
https://github.com/skip-mev/block-sdk/blob/d3c131de53abdbcb1c85f716924f10233c66a6e5/block/proposals/proposals.go#L51-L59

This makes `/cosmos/tx/v1beta1/txs/block/` query always return the following error. This query attempt to decode all txs in a block, so you need to avoid using txs field to pass proposal metadata between prepare and process.

```shell
{
  "code": 2,
  "message": "codespace sdk code 2: tx parse error: expected 2 wire type, got 0",
  "details": []
}
```

or need to provide custom tx query service handler :)

**Comment by davidterpay** [comment]
hey! thanks for bringing this up. unfortunately, there isn't much we can do in terms of modifying the upstream `GetBlockWithTxs` since our proposals must include this additional meta-data, however, a potential work around for now might be to utilize `GetBlockByHeight` (ref: https://github.com/cosmos/cosmos-sdk/blob/e269c6d5dbbce9486ee02ef3757df1eb586656f5/client/grpc/cmtservice/service.go#L82-L103) instead.

**Comment by davidterpay** [comment]
we are planning on adding a separate gRPC service for the app-side mempool so that you can query its size, txs waiting to be included in blocks, and more.

**Comment by beer-1** [comment]
yea okay that's enough.
Maybe we can make custom tx service to exclude first tx in a block for txs query temporary.

**Comment by davidterpay** [comment]
Hey, just following up: https://github.com/skip-mev/block-sdk/pull/236. this PR will remove the meta-info tx from being included so the RPC should work as it did before. Going to reopen until this is merged.

**Comment by davidterpay** [comment]
Code has been merged, we are now load testing.
